version: '3.4'

services:
  deploy:
    build:
      context: .
    volumes:
    - '~/.aws:/root/.aws'

  ghost:
    image: ghost:3.20.1
    environment:
      DEBUG: '*'
      logging__level: debug
    ports:
      - 80:80
      - 2368:2368
      - 4200:4200

  smtp-password:
    build:
      context: smtp/
    command:
      - --region
      - us-east-1
      - --secret
      - YOUR_IAM_SECRET_ACCESS_KEY # from "SecretAccessKey" stack output

  static-site:
    build:
      context: .
      args:
        GHOST_HOME_PAGE: https://existing-ghost-site-home-page
        STATIC_SITE_HOME_PAGE: https://static-site-home-page
      dockerfile: static-site.dockerfile
    ports:
    - 8080:8080
