version: '3.4'

services:
  deploy:
    env_file:
      - .env
    build:
      context: .
    volumes:
    - '~/.aws:/root/.aws'

  ghost:
    image: ghost:3.20.1
    environment:
      DEBUG: '*'
      logging__level: debug
    ports:
      - 80:80
      - 2368:2368
      - 4200:4200

  smtp-password:
    build:
      context: smtp/
    command:
      - --region
      - $AWS_DEFAULT_REGION
      - --secret
      - $YOUR_IAM_SECRET_ACCESS_KEY

  static-site:
    build:
      context: .
      args:
        GHOST_HOME_PAGE: $GHOST_HOME_PAGE
        STATIC_SITE_HOME_PAGE: $STATIC_SITE_HOME_PAGE
      dockerfile: static-site.dockerfile
    ports:
    - 8080:8080
