version: '3.4'

services:
  deploy:
    build:
      context: .
    volumes:
    - '~/.aws:/root/.aws'

  ghost:
    image: ghost:3.20.1
    environment:
      DEBUG: '*'
      logging__level: debug
    ports:
      - 80:80
      - 2368:2368
      - 4200:4200
